# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:
- script: |
    python -m pip install --upgrade pip setuptools wheel django
    pip install -r requirements.txt
    pip install unittest-xml-reporting
    pip install awscli
  displayName: 'Install prerequisites including AWS tools'
  
- script: |
    git clone https://github.com/squirke1977/munki-pkg.git
  displayName: 'Install Munki-Pkg - Hello World!'
  
- script: |
    cd munki-pkg
    ./munkipkg TurnOffBluetooth/

#- task: Xcode@5
#  inputs:
#    scheme: ''
#    sdk: 'iphoneos'
#    configuration: 'Release'
#    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
