# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:
- script: |
    python -m pip install --upgrade pip
    pip install awscli
    git clone https://github.com/squirke1977/munki-pkg.git
  displayName: 'Install prerequisites including AWS tools'
  
- script: |
     git clone https://github.com/ThoughtWorks-Identity/installapplications
  displayName: 'Grab TW InstallApplications'
  
- script: |
    cd munki-pkg
    ./munkipkg TurnOffBluetooth/
   displayName: 'Actually building a package!'
   
- script: |
    cd munki-pkg
    ./munkipkg SuppressSetupAssistant/
   displayName: 'Actually building another package!'


#- task: Xcode@5
#  inputs:
#    scheme: ''
#    sdk: 'iphoneos'
#    configuration: 'Release'
#    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
