# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:
- task: DownloadSecureFile@1
  displayName 'Work damn you, work.'
  inputs:
    secureFile: 'money.gif'
- script: |
    python -m pip install --upgrade pip
    pip install awscli
    pip install requests
    git clone https://github.com/squirke1977/munki-pkg.git
  displayName: 'Install prerequisites including AWS tools'

#- task: InstallAppleCertificate@2
#  displayName: 'Install an Apple certificate'
#  inputs:
#    certSecureFile: 'test_azure_cert.p12'
#
#    certPwd: '$(signing_key)'

- script: |
     git clone https://github.com/ThoughtWorks-Identity/installapplications
  displayName: 'Grab TW InstallApplications'

- script: |
    ./munki-pkg/munkipkg installapplications
  displayName: 'Build TW InstallApplications'

#- script: |
#    cd munki-pkg
#    ./munkipkg TurnOffBluetooth/
#  displayName: 'Actually building a package!'



#- task: Xcode@5
#  inputs:
#    scheme: ''
#    sdk: 'iphoneos'
#    configuration: 'Release'
#    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
